version: '3'
services:
  app:
    build: .
    environment:
      - SVELTE_URL_WITH_SLASH=80
    ports:
      - "80:5173"
      - "4696:4696"
    command: /app/entrypoint.sh
    # networks:
    #   default:
    #     driver: bridge
